# -*- mode: python; -*-

Import(['env'])

env = env.Clone()

env.SConscript(
    dirs=[
#        'dial',
#        'dial_api_key',
#        'modules',
#        'mlmodel',
        'motor',
#        'camera',
    ],
    exports={
        'env' : env.Clone(),
    },
)
