# -*- mode: python; -*-

Import(['env'])

env = env.Clone()

env.AppendUnique(
    CPPPATH=[
        '$VARIANT_DIR/src/viam/api/gen',
        '$VARIANT_DIR/src',
        '$VARIANT_DIR/src/viam/api/gen/viam/api',
        '$VARIANT_DIR/src/viam/api',
    ],
    LIBPATH=[
        '#',
        '$VARIANT_DIR/src/viam/api',
        '$VARIANT_DIR/src/viam/sdk',
    ],
    CPPDEFINES=[
        'BOOST_ALL_DYN_LINK',
    ]
 )

env.SConscript(
    dirs=[
        'viam',
    ],
    exports={
        'env' : env.Clone(),
    },
)
